# Generated by Django 3.2.3 on 2021-05-22 15:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('contribution', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('business_type', models.CharField(choices=[('t1', 'type1'), ('t2', 'type2'), ('t3', 'type3')], default='t1', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='phoneno',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None, unique=True),
        ),
        migrations.CreateModel(
            name='UserFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('business_name', models.CharField(max_length=30)),
                ('business_address', models.CharField(max_length=50)),
                ('business_type', models.CharField(choices=[('t1', 'type1'), ('t2', 'type2'), ('t3', 'type3')], default='t1', max_length=2)),
                ('business_plan', models.CharField(choices=[('p1', 'plan1'), ('p2', 'plan2'), ('p3', 'plan3')], default='p1', max_length=2)),
                ('fb_id', models.CharField(max_length=30)),
                ('insta_id', models.CharField(max_length=30)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users', to_field='phoneno')),
            ],
        ),
        migrations.CreateModel(
            name='user_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users', to_field='phoneno')),
            ],
        ),
        migrations.CreateModel(
            name='sent_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_schedule', models.DateField()),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userfields')),
                ('theme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.themes')),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('designer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.designer')),
                ('theme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.themes')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None)),
                ('status', models.BooleanField(default=False)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userfields')),
            ],
        ),
    ]
